GAME_ZIP64.onButtonPress(GAME_ZIP64.ZIP64ButtonPins.Up, GAME_ZIP64.ZIP64ButtonEvents.Down, function () {
    display.show()
    display.setPixelColorAt(3, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(4, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(11, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(12, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(19, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(20, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(27, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(28, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(35, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(36, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(43, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(44, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(51, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(52, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(59, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(60, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(10, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(13, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(18, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(21, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(17, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(22, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(24, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(25, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(26, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(29, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(30, GAME_ZIP64.colors(ZipLedColors.Red))
    display.setPixelColorAt(31, GAME_ZIP64.colors(ZipLedColors.Red))
    basic.pause(1357)
})
let display: GAME_ZIP64.ZIP64Display = null
display = GAME_ZIP64.createZIP64Display()
display.setBrightness(50)
